version: '3'
services:
  kraken-postgres:
    container_name: kraken-postgres
    build: ./postgres
    volumes:
      - type: volume
        source: kraken-postgres-data
        target: /var/lib/postgresql/data
    ports:
      - 6008:5432
    restart: always
    networks:
      - kraken-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0vFfKbaozFM6PNirdmruXKWzoXa
      - POSTGRES_HOST_AUTH_METHOD=md5
  kraken-backend:
    build: ./kraken
    ports:
      - 6007:6007
    networks:
      - kraken-net

volumes:
  kraken-postgres-data: null

networks:
  kraken-net: null
