[package]
name = "kraken"
version = "0.1.0"
authors = ["Alexander Chudinov <alexander.chudinov@icloud.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
json = "0.12.4"
postgres = "0.19.2"