[package]
name = "kraken"
version = "0.1.0"
authors = ["Alexander Chudinov <alexander.chudinov@icloud.com>"]
edition = "2021"

[dependencies]
actix-web = "3"
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"